SELECT * FROM Cleaned_file$

--1st Query--
# Which apps have the highest rating in the given available dataset?
SELECT TOP 5 Rating, App
FROM Cleaned_file$ 
ORDER BY Rating desc

--2nd Query--
# What are the number of installs and reviews for the above apps?Return the apps with the highest reviews to the top.
SELECT TOP 5 Rating, App, Installs,Reviews
FROM Cleaned_file$ 
ORDER BY Rating desc 

--3rd Query--
# Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
SELECT TOP 1 Reviews, App, Category
FROM Cleaned_file$
ORDER BY Reviews DESC

--4th Query--
# What is the total amount of revenue generated by the google play store by hosting apps? 
SELECT SUM(Installs*Price) AS Revenue
FROM Cleaned_file$

--5th Query--
# Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
SELECT TOP 1 Category, Installs
FROM Cleaned_file$
ORDER BY Installs DESC

--6th Query--
# Which Genre has the most number of published apps?
SELECT TOP 5 Genres, App
FROM Cleaned_file$
ORDER BY Installs DESC

--7th Query--
# Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top.
SELECT Distinct Category, App, Installs
FROM Cleaned_file$
WHERE Category='GAME'
ORDER BY Installs DESC

--8th Query--
# Provide the list of apps that can work on android version 4.0.3 and UP.
SELECT App, [Android Ver]
FROM Cleaned_file$
WHERE [Android Ver] >= '4.0.3 and up'

--9th Query--
# How many apps from the given data set are free? Also, provide the number of paid apps.
SELECT COUNT(*) AS Free_Apps, 
	(SELECT COUNT(*) 
	FROM Cleaned_file$
	WHERE Type='Paid') AS Paid_Apps
FROM Cleaned_file$
WHERE Type='Free'

--10th Query--
# Which is the best dating app?
SELECT TOP 1 Reviews AS Most_Reviewed, App
FROM Cleaned_file$
WHERE Category='Dating'
ORDER BY Most_Reviewed DESC

--11th Query--
# Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app "10 best foods for you" and compare them.
SELECT COUNT(Sentiment) AS Positive_Sentiment,
	(SELECT COUNT(Sentiment) 
	FROM Playstore_review$
	WHERE Sentiment='negative' AND App='10 best foods for you') AS Negative_Sentiment
FROM Playstore_review$
WHERE Sentiment='Positive' AND App='10 best foods for you'

--12th Query--
# Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT Translated_Review AS Polarity_Subjectivity_1
FROM playstore_reviews$
WHERE App='ASUS SuperNote' AND Sentiment_Polarity=1 AND Sentiment_Subjectivity=1

--13th Query--
# Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat
SELECT Translated_Review As Total_Neutral_comments
FROM playstore_reviews$
WHERE Sentiment='neutral' AND App= 'Abs training-burn belly fat'

--14th Query--
# Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
SELECT App,Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity 
FROM playstore_reviews$
WHERE Sentiment='negative' AND App= 'Adobe Acrobat Reader'

